//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiaTools.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TiaTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DATA_BLOCK &quot;AI_$VAR_NAME$&quot;
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///NON_RETAIN
        ///&quot;FB_AI&quot;
        ///
        ///BEGIN
        ///
        ///END_DATA_BLOCK
        ///.
        /// </summary>
        internal static string DB_AI {
            get {
                return ResourceManager.GetString("DB_AI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DATA_BLOCK &quot;AQ_$VAR_NAME$&quot;
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///NON_RETAIN
        ///&quot;FB_AQ&quot;
        ///
        ///BEGIN
        ///
        ///END_DATA_BLOCK
        ///.
        /// </summary>
        internal static string DB_AQ {
            get {
                return ResourceManager.GetString("DB_AQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DATA_BLOCK &quot;DI_$VAR_NAME$&quot;
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///NON_RETAIN
        ///&quot;FB_DI&quot;
        ///
        ///BEGIN
        ///
        ///END_DATA_BLOCK
        ///.
        /// </summary>
        internal static string DB_DI {
            get {
                return ResourceManager.GetString("DB_DI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DATA_BLOCK &quot;DQ_$VAR_NAME$&quot;
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///NON_RETAIN
        ///&quot;FB_DQ&quot;
        ///
        ///BEGIN
        ///
        ///END_DATA_BLOCK
        ///.
        /// </summary>
        internal static string DB_DQ {
            get {
                return ResourceManager.GetString("DB_DQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DATA_BLOCK &quot;DB_Msg&quot;
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///NON_RETAIN
        ///   VAR 
        ///      Msg : &quot;Msg&quot;;
        ///   END_VAR
        ///
        ///
        ///BEGIN
        ///
        ///END_DATA_BLOCK
        ///
        ///.
        /// </summary>
        internal static string DB_Msg {
            get {
                return ResourceManager.GetString("DB_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DATA_BLOCK &quot;DB_SM&quot;
        ///{ S7_Optimized_Access := &apos;FALSE&apos; }
        ///VERSION : 0.1
        ///NON_RETAIN
        ///   STRUCT 
        ///      SM : Array[0..$SM_TOT_NB$] of &quot;SM_GEN&quot;;
        ///   END_STRUCT;
        ///
        ///BEGIN
        ///
        ///END_DATA_BLOCK.
        /// </summary>
        internal static string DB_SM {
            get {
                return ResourceManager.GetString("DB_SM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FUNCTION_BLOCK &quot;FB_AI&quot;
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///   VAR_INPUT 
        ///      Signal : Int;
        ///   END_VAR
        ///
        ///   VAR 
        ///      STATUS : &quot;AI_STATUS&quot;;
        ///      CONFIG : &quot;AI_CONFIG&quot;;
        ///      ALARM : &quot;AI_ALARM&quot;;
        ///      AUX : &quot;AI_AUX&quot;;
        ///      HMI { S7_SetPoint := &apos;False&apos;} : &quot;HMI_IO&quot;;
        ///   END_VAR
        ///
        ///
        ///BEGIN
        ///	//********************************************************************//
        ///	//Name: FB_AI
        ///	//Version: 0.1
        ///	//Description: FB_AI
        ///	//Developer: Topcast
        ///	//****************************************** [stringa troncata]&quot;;.
        /// </summary>
        internal static string FB_AI {
            get {
                return ResourceManager.GetString("FB_AI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FUNCTION_BLOCK &quot;FB_AQ&quot;
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///   VAR_OUTPUT 
        ///      Signal : Int;
        ///   END_VAR
        ///
        ///   VAR 
        ///      COMMAND : &quot;AQ_COMMAND&quot;;
        ///      CONFIG { S7_SetPoint := &apos;False&apos;} : &quot;AQ_CONFIG&quot;;
        ///      AUX { S7_SetPoint := &apos;False&apos;} : &quot;AQ_AUX&quot;;
        ///      HMI : &quot;HMI_IO&quot;;
        ///   END_VAR
        ///
        ///
        ///BEGIN
        ///	//********************************************************************//
        ///	//Name: FB_AO
        ///	//Version: 0.1
        ///	//Description: FB_AO
        ///	//Developer: Topcast
        ///	//**************************************** [stringa troncata]&quot;;.
        /// </summary>
        internal static string FB_AQ {
            get {
                return ResourceManager.GetString("FB_AQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FUNCTION_BLOCK &quot;FB_DI&quot;
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///   VAR_INPUT 
        ///      Signal : Bool;
        ///   END_VAR
        ///
        ///   VAR 
        ///      STATUS : &quot;DI_STATUS&quot;;
        ///      CONFIG { S7_SetPoint := &apos;False&apos;} : &quot;DI_CONFIG&quot;;
        ///      AUX { S7_SetPoint := &apos;False&apos;} : &quot;DI_AUX&quot;;
        ///      HMI : &quot;HMI_IO&quot;;
        ///   END_VAR
        ///
        ///
        ///BEGIN
        ///	//********************************************************************//
        ///	//Name: FB_DI
        ///	//Version: x.x
        ///	//Description: FB_DI
        ///	//Developer: Topcast
        ///	//****************************************** [stringa troncata]&quot;;.
        /// </summary>
        internal static string FB_DI {
            get {
                return ResourceManager.GetString("FB_DI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FUNCTION_BLOCK &quot;FB_DQ&quot;
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///   VAR_OUTPUT 
        ///      Signal : Bool;
        ///   END_VAR
        ///
        ///   VAR 
        ///      STATUS : &quot;DQ_STATUS&quot;;
        ///      COMMAND : &quot;DQ_COMMAND&quot;;
        ///      CONFIG { S7_SetPoint := &apos;False&apos;} : &quot;DQ_CONFIG&quot;;
        ///      AUX : &quot;DQ_AUX&quot;;
        ///      HMI : &quot;HMI_IO&quot;;
        ///   END_VAR
        ///
        ///
        ///BEGIN
        ///	//********************************************************************//
        ///	//Name: FB_DO
        ///	//Version: x.x
        ///	//Description: FB_DO
        ///	//Developer: Topcast
        ///	//************************************ [stringa troncata]&quot;;.
        /// </summary>
        internal static string FB_DQ {
            get {
                return ResourceManager.GetString("FB_DQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FUNCTION &quot;FC_AI&quot; : Void
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///
        ///BEGIN
        ///	//********************************************************************//
        ///	//Name: FC_AI
        ///	//Version: x.x
        ///	//Description: FC_AI
        ///	//Developer: Topcast
        ///	//********************************************************************//
        ///	
        ///	//ELESMPIO DI RCHIAMO FC_AI
        ///	//********************************************************************//
        ///	//Si considera un ingresso analogico definito sulla tabella delle variabili PLC come &quot;INGR [stringa troncata]&quot;;.
        /// </summary>
        internal static string FC_AI {
            get {
                return ResourceManager.GetString("FC_AI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FUNCTION &quot;FC_AI_Config&quot; : Void
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///
        ///BEGIN
        ///	//********************************************************************//
        ///	//Name: FC_AI_Config
        ///	//Version: x.x
        ///	//Description: FC_AI_Config
        ///	//Developer: Topcast
        ///	//********************************************************************//
        ///
        ///	//ESEMPIO DI CONFIGURAZIONE 
        ///	//********************************************************************//
        ///	// &quot;AI_INGRESSO_ANALOGICO&quot;.CONFIG.Name := 326; Indice Dell&apos;elenco tes [stringa troncata]&quot;;.
        /// </summary>
        internal static string FC_AI_Config {
            get {
                return ResourceManager.GetString("FC_AI_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 	//AI_$VAR_NAME$
        ///	//********************************************************************//
        ///	&quot;AI_$VAR_NAME$&quot;.CONFIG.HighScaleValue := 0;
        ///	&quot;AI_$VAR_NAME$&quot;.CONFIG.LowScaleValue := 0;
        ///	&quot;AI_$VAR_NAME$&quot;.CONFIG.HighLimit := 0;
        ///	&quot;AI_$VAR_NAME$&quot;.CONFIG.LowLimit := 0;
        ///	&quot;AI_$VAR_NAME$&quot;.CONFIG.ManualCompValue := 0;
        ///	&quot;AI_$VAR_NAME$&quot;.CONFIG.ManualScalingValue := 0;
        ///	&quot;AI_$VAR_NAME$&quot;.CONFIG.AlarmDelay := T#5S;
        ///	&quot;AI_$VAR_NAME$&quot;.CONFIG.IsBipolar := 0;
        ///	&quot;AI_$VAR_NAME$&quot;.CONFIG.DoNotScale := 0;
        ///	&quot;AI_$VAR_NAME$&quot;.CONFI [stringa troncata]&quot;;.
        /// </summary>
        internal static string FC_AI_Config_Part {
            get {
                return ResourceManager.GetString("FC_AI_Config_Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a //AI_$VAR_NAME$
        /////********************************************************************//
        ///&quot;AI_$VAR_NAME$&quot;(&quot;$VAR_NAME$&quot;);
        ///.
        /// </summary>
        internal static string FC_AI_Part {
            get {
                return ResourceManager.GetString("FC_AI_Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FUNCTION &quot;FC_AQ&quot; : Void
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///
        ///BEGIN
        ///	//********************************************************************//
        ///	//Name: FC_AQ
        ///	//Version: x.x
        ///	//Description: FC_AQ
        ///	//Developer: Topcast
        ///	//********************************************************************//
        ///	
        ///	//ELESMPIO DI RCHIAMO FB_AQ
        ///	//********************************************************************//
        ///	//Si considera una uscita analogica definito sulla tabella delle variabili PLC come &quot;USCIT [stringa troncata]&quot;;.
        /// </summary>
        internal static string FC_AQ {
            get {
                return ResourceManager.GetString("FC_AQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FUNCTION &quot;FC_AQ_Config&quot; : Void
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///
        ///BEGIN
        ///	//********************************************************************//
        ///	//Name: FC_AQ_Config
        ///	//Version: x.x
        ///	//Description: FC_AQ_Config
        ///	//Developer: Topcast
        ///	//********************************************************************//
        ///	
        ///	//ESEMPIO DI CONFIGURAZIONE
        ///	//********************************************************************//
        ///	// &quot;AQ_USCITA_ANALOGICA.CONFIG.Name := 4226; Indice Dell&apos;elenco testi [stringa troncata]&quot;;.
        /// </summary>
        internal static string FC_AQ_Config {
            get {
                return ResourceManager.GetString("FC_AQ_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 	//AQ_$VAR_NAME$
        ///	//********************************************************************//
        ///	&quot;AQ_$VAR_NAME$&quot;.CONFIG.HighUnscaleLimit := 0;
        ///	&quot;AQ_$VAR_NAME$&quot;.CONFIG.LowUnscaleLimit := 0;
        ///	&quot;AQ_$VAR_NAME$&quot;.CONFIG.IsBipolar := 0;
        ///.
        /// </summary>
        internal static string FC_AQ_Config_Part {
            get {
                return ResourceManager.GetString("FC_AQ_Config_Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a //AQ_$VAR_NAME$
        /////********************************************************************//
        ///&quot;AQ_$VAR_NAME$&quot;(&quot;$VAR_NAME$&quot;);
        ///.
        /// </summary>
        internal static string FC_AQ_Part {
            get {
                return ResourceManager.GetString("FC_AQ_Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FUNCTION &quot;FC_DI&quot; : Void
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///
        ///BEGIN
        ///	//********************************************************************//
        ///	//Name: FC_DI
        ///	//Version: x.x
        ///	//Description: FI_DI
        ///	//Developer: Topcast
        ///	//********************************************************************//
        ///	
        ///	//ELESMPIO DI RCHIAMO FB_DI
        ///	//********************************************************************//
        ///	//Si considera un ingresso digitale definito sulla tabella delle variabili PLC come &quot;INGRE [stringa troncata]&quot;;.
        /// </summary>
        internal static string FC_DI {
            get {
                return ResourceManager.GetString("FC_DI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FUNCTION &quot;FC_DI_Config&quot; : Void
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///
        ///BEGIN
        ///	//********************************************************************//
        ///	//Name: FC_DI_Config
        ///	//Version: x.x
        ///	//Description: FC_DI_Config
        ///	//Developer: Topcast
        ///	//********************************************************************//
        ///	
        ///	//ESEMPIO DI CONFIGURAZIONE
        ///	//********************************************************************//
        ///	//&quot;DI_INGRESSO_DIGITALE&quot;.CONFIG.Name := 1180; Indice Dell&apos;elenco test [stringa troncata]&quot;;.
        /// </summary>
        internal static string FC_DI_Config {
            get {
                return ResourceManager.GetString("FC_DI_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a //DI_$VAR_NAME$
        /////********************************************************************//
        ///&quot;DI_$VAR_NAME$&quot;.CONFIG.DebounceTime := T#0MS;
        ///.
        /// </summary>
        internal static string FC_DI_Config_Part {
            get {
                return ResourceManager.GetString("FC_DI_Config_Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a //DI_$VAR_NAME$
        /////********************************************************************//
        ///&quot;DI_$VAR_NAME$&quot;(&quot;$VAR_NAME$&quot;);
        ///.
        /// </summary>
        internal static string FC_DI_Part {
            get {
                return ResourceManager.GetString("FC_DI_Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FUNCTION &quot;FC_DQ&quot; : Void
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///
        ///BEGIN
        ///	//********************************************************************//
        ///	//Name: FC_DQ
        ///	//Version: x.x
        ///	//Description: FC_DQ
        ///	//Developer: Topcast
        ///	//********************************************************************//
        ///	
        ///	//ELESMPIO DI RCHIAMO FB_DQ
        ///	//********************************************************************//
        ///	//Si considera una uscita digitale definito sulla tabella delle variabili PLC come &quot;USCITA [stringa troncata]&quot;;.
        /// </summary>
        internal static string FC_DQ {
            get {
                return ResourceManager.GetString("FC_DQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FUNCTION &quot;FC_DQ_Config&quot; : Void
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///
        ///BEGIN
        ///	//********************************************************************//
        ///	//Name: FC_DQ_Config
        ///	//Version: x.x
        ///	//Description: FC_DQ_Config
        ///	//Developer: Topcast
        ///	//********************************************************************//
        ///	
        ///	//ESEMPIO DI CONFIGURAZIONE
        ///	//********************************************************************//
        ///	// &quot;DQ_USCITA_DIGITALE&quot;.CONFIG.OFFDelay := T#0MS; Tempo di ritardo su [stringa troncata]&quot;;.
        /// </summary>
        internal static string FC_DQ_Config {
            get {
                return ResourceManager.GetString("FC_DQ_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a //DQ_$VAR_NAME$
        /////********************************************************************//
        ///&quot;DQ_$VAR_NAME$&quot;.CONFIG.OFFDelay := T#0MS;
        ///&quot;DQ_$VAR_NAME$&quot;.CONFIG.OnDelay := T#0MS;
        ///.
        /// </summary>
        internal static string FC_DQ_Config_Part {
            get {
                return ResourceManager.GetString("FC_DQ_Config_Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a //DQ_$VAR_NAME$
        /////********************************************************************//
        ///&quot;DQ_$VAR_NAME$&quot;(&quot;$VAR_NAME$&quot;);
        ///.
        /// </summary>
        internal static string FC_DQ_Part {
            get {
                return ResourceManager.GetString("FC_DQ_Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FUNCTION &quot;FC_Msg_Config&quot; : Void
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///   VAR_TEMP 
        ///      i : Int;
        ///   END_VAR
        ///
        ///BEGIN
        ///	//********************************************************************//
        ///	//Name: FC_Msg_Config
        ///	//Version: 0.1
        ///	//Description: FC_Msg_Config
        ///	//Developer: Topcast
        ///	//********************************************************************//
        ///
        ///	//Msg General Config
        ///	//********************************************************************//
        ///	&quot;DB_Msg&quot;.Msg.Config.MsgHmiWordNb [stringa troncata]&quot;;.
        /// </summary>
        internal static string FC_Msg_Config_Begin {
            get {
                return ResourceManager.GetString("FC_Msg_Config_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 	//Msg $MSG_NUMBER$ - $MSG_DEVICE$ - $MSG_TEXT$
        ///	//********************************************************************//
        ///	&quot;DB_Msg&quot;.Msg.Msg[$MSG_NUMBER$].Config.Reaction[$SM_NUMBER$] := $MSG_REACTION$;.
        /// </summary>
        internal static string FC_Msg_Config_Body {
            get {
                return ResourceManager.GetString("FC_Msg_Config_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a END_FUNCTION.
        /// </summary>
        internal static string FC_Msg_Config_End {
            get {
                return ResourceManager.GetString("FC_Msg_Config_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FUNCTION &quot;FC_Msg_Handler&quot; : Void
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///   VAR_IN_OUT 
        ///      Msg : &quot;Msg&quot;;
        ///   END_VAR
        ///
        ///   VAR_TEMP 
        ///      i : Int;
        ///      ToBeAck : Int;
        ///   END_VAR
        ///
        ///
        ///BEGIN
        ///	//********************************************************************//
        ///	//Name: FC_Msg_Handler
        ///	//Version: 0.1
        ///	//Description: FC_Msg_Handler
        ///	//Developer: Topcast
        ///	//********************************************************************//
        ///
        ///	//Reset Msg Pending
        ///	//***************************** [stringa troncata]&quot;;.
        /// </summary>
        internal static string FC_Msg_Handler_Begin {
            get {
                return ResourceManager.GetString("FC_Msg_Handler_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a     //Msg Reaction
        ///	//********************************************************************//
        ///    FOR #i := 0 TO #Msg.Config.MsgMaxNb DO
        ///        &quot;FC_Msg_Reaction&quot;(MsgNb := #i,
        ///                          Ack := &quot;DB_Msg&quot;.Msg.Ack,
        ///                          Msg := &quot;DB_Msg&quot;.Msg);
        ///    END_FOR;
        ///.
        /// </summary>
        internal static string FC_Msg_Handler_Body_None {
            get {
                return ResourceManager.GetString("FC_Msg_Handler_Body_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a     //Msg Reaction
        ///	//********************************************************************//
        ///    FOR #i := 0 TO #Msg.Config.MsgMaxNb DO
        ///        &quot;FC_Msg_Reaction&quot;(MsgNb := #i,
        ///                          Ack := &quot;DB_Msg&quot;.Msg.Ack,
        ///                          Msg := &quot;DB_Msg&quot;.Msg);
        ///    
        ///        &quot;FC_Msg_Store_Sql&quot;(FOData := &quot;DB_FO_Data&quot;.FOData,
        ///                           MsgNb := #i,
        ///                           Msg := &quot;DB_Msg&quot;.Msg);
        ///    END_FOR;
        ///.
        /// </summary>
        internal static string FC_Msg_Handler_Body_Store {
            get {
                return ResourceManager.GetString("FC_Msg_Handler_Body_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 	//Ack
        ///	//********************************************************************//
        ///	IF #Msg.Ack THEN
        ///		#Msg.Ack := 0;
        ///	END_IF;
        ///	
        ///	            
        ///END_FUNCTION.
        /// </summary>
        internal static string FC_Msg_Handler_End {
            get {
                return ResourceManager.GetString("FC_Msg_Handler_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FUNCTION &quot;FC_Msg_Reaction&quot; : Void
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///   VAR_INPUT 
        ///      MsgNb : Int;
        ///      Ack : Bool;
        ///   END_VAR
        ///
        ///   VAR_IN_OUT 
        ///      Msg : &quot;Msg&quot;;
        ///   END_VAR
        ///
        ///   VAR_TEMP 
        ///      i : Int;
        ///      HmiWordNb : Int;
        ///      HmiBitNb : Int;
        ///   END_VAR
        ///
        ///
        ///BEGIN
        ///    //********************************************************************//
        ///    //Name: FC_Msg_Reaction
        ///    //Version: 0.1
        ///    //Description: FC_Msg_Reaction
        ///    //Developer: Topcast
        ///    //************** [stringa troncata]&quot;;.
        /// </summary>
        internal static string FC_Msg_Reaction {
            get {
                return ResourceManager.GetString("FC_Msg_Reaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FUNCTION &quot;FC_Msg_Store_Sql&quot; : Void
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///   VAR_INPUT 
        ///      MsgNb : Int;
        ///      FOData : Array[0..11] of &quot;Fo_DATA&quot;;
        ///   END_VAR
        ///
        ///   VAR_IN_OUT 
        ///      Msg : &quot;Msg&quot;;
        ///   END_VAR
        ///
        ///   VAR_TEMP 
        ///      i : Int;
        ///   END_VAR
        ///
        ///
        ///BEGIN
        ///    //********************************************************************//
        ///    //Name: FC_Msg_Store_Sql
        ///    //Version: 0.1
        ///    //Description: FC_Msg_Store_Sql
        ///    //Developer: Topcast
        ///    //********************************** [stringa troncata]&quot;;.
        /// </summary>
        internal static string FC_Msg_Store_Sql {
            get {
                return ResourceManager.GetString("FC_Msg_Store_Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FUNCTION &quot;FC_Msg_Trigger&quot; : Void
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///
        ///BEGIN
        ///	//********************************************************************//
        ///	//Name: FC_Msg_Trigger
        ///	//Version: 0.1
        ///	//Description: FC_Msg_Trigger
        ///	//Developer: Topcast
        ///	//********************************************************************//
        ///
        ///.
        /// </summary>
        internal static string FC_Msg_Trigger_Begin {
            get {
                return ResourceManager.GetString("FC_Msg_Trigger_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 	//Msg $MSG_NUMBER$ - $MSG_DEVICE$ - $MSG_TEXT$
        ///	//********************************************************************//
        ///	&quot;DB_Msg&quot;.Msg.Msg[$MSG_NUMBER$].Trigger := FALSE;
        ///.
        /// </summary>
        internal static string FC_Msg_Trigger_Body {
            get {
                return ResourceManager.GetString("FC_Msg_Trigger_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FUNCTION &quot;FC_SM_$SM_NB$&quot; : Void
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///   VAR_TEMP 
        ///      SMN : Int;
        ///   END_VAR
        ///
        ///
        ///BEGIN
        ///	//********************************************************************//
        ///	//Name: FC_SM_$SM_NB$
        ///	//Version: x.x
        ///	//Description: State Machine $SM_NB$ ($SM_NAME$)
        ///	//Developer: Topcast
        ///	//********************************************************************//
        ///
        ///	//DESCRIZIONE
        ///	//********************************************************************//
        ///	// Questo blocc [stringa troncata]&quot;;.
        /// </summary>
        internal static string FC_SM {
            get {
                return ResourceManager.GetString("FC_SM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FUNCTION &quot;FC_SM_Call&quot; : Void
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///
        ///BEGIN
        ///	//********************************************************************//
        ///	//Name: FC_SM_Call                                     
        ///	//Version: 0.1
        ///	//Description: StateMachine Call
        ///	//Developer: Topcast
        ///	//********************************************************************//
        ///	
        ///
        ///
        ///.
        /// </summary>
        internal static string FC_SM_Call {
            get {
                return ResourceManager.GetString("FC_SM_Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FUNCTION &quot;FC_SM_Common&quot; : Void
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///   VAR_INPUT 
        ///      SMN : Int;
        ///      StartPhase : Int;
        ///      Autostart : Bool;
        ///   END_VAR
        ///
        ///   VAR_IN_OUT 
        ///      MsgPause : Bool;
        ///      MsgStop : Bool;
        ///   END_VAR
        ///
        ///
        ///BEGIN
        ///	
        ///	//********************************************************************//
        ///	//Name: FC_SM_Common
        ///	//Version: x.x
        ///	//Description: FC_SM_Common
        ///	//Developer: Topcast
        ///	//********************************************************************//
        ///	 [stringa troncata]&quot;;.
        /// </summary>
        internal static string FC_SM_Common {
            get {
                return ResourceManager.GetString("FC_SM_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FUNCTION &quot;FC_Hmi_SM_$SM_NAME$&quot; : Void
        ///{ S7_Optimized_Access := &apos;FALSE&apos; }
        ///VERSION : 0.1
        ///   VAR_TEMP 
        ///      FILL_RET_VAL : Int;
        ///      FILL_B_VAL : Byte;
        ///   END_VAR
        ///
        ///   VAR CONSTANT 
        ///      SMN : Int := 1;
        ///   END_VAR
        ///
        ///
        ///BEGIN
        ///	//********************************************************************//
        ///	//Name: FC_Hmi_SM_$SM_NAME$
        ///	//Version: x.x
        ///	//Description: SM $SM_NAME$ HMI Management
        ///	//Developer: Topcast
        ///	//********************************************************************//
        ///	
        ///	CASE &quot;DB [stringa troncata]&quot;;.
        /// </summary>
        internal static string FC_SM_Hmi {
            get {
                return ResourceManager.GetString("FC_SM_Hmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a  	        //$PHASE_NAME$
        ///	        //********************************************************************// 
        ///	    &quot;$PHASE_NAME$&quot;:
        ///	        
        ///			;
        ///	        //HMI Management
        ///			(*Hmi Logic Here*).
        /// </summary>
        internal static string FC_SM_Hmi_Step {
            get {
                return ResourceManager.GetString("FC_SM_Hmi_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FUNCTION &quot;FC_SM_Pause_Seq&quot; : Void
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///   VAR_INPUT 
        ///      SMN : Int;
        ///   END_VAR
        ///
        ///
        ///BEGIN
        ///	//********************************************************************//
        ///	//Name: FC_SM_Pause_Seq
        ///	//Version: x.x
        ///	//Description: FC_SM_Pause_Seq
        ///	//Developer: Topcast
        ///	//********************************************************************//
        ///
        ///	//UTILIZZO
        ///	//********************************************************************//
        ///	//Definire per ogni macchina a  [stringa troncata]&quot;;.
        /// </summary>
        internal static string FC_SM_Pause_Seq {
            get {
                return ResourceManager.GetString("FC_SM_Pause_Seq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FUNCTION &quot;FC_$PHASE_NAME$&quot; : Void
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///
        ///BEGIN
        ///	//********************************************************************//
        ///	//Name: FC_$PHASE_NAME$
        ///	//Version: x.x
        ///	//Description: FC_$PHASE_NAME$
        ///	//Developer: Topcast
        ///	//********************************************************************//
        ///
        ///	//Step Name 
        ///	&quot;DB_SM&quot;.SM[$SM_NB$].Status.StepName := &apos;$PHASE_NAME$&apos;;
        ///	
        ///	//Step Logic
        ///	(*Add Phase Logic Here*)
        ///	
        ///	//Reset Hmi Controls
        ///	(*Reset Hmi Controls He [stringa troncata]&quot;;.
        /// </summary>
        internal static string FC_SM_Phase {
            get {
                return ResourceManager.GetString("FC_SM_Phase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FUNCTION &quot;FC_SM_Reset_Seq&quot; : Void
        ///{ S7_Optimized_Access := &apos;FALSE&apos; }
        ///VERSION : 0.1
        ///   VAR_INPUT 
        ///      SMN : Int;
        ///   END_VAR
        ///
        ///
        ///BEGIN
        ///	//********************************************************************//
        ///	//Name: FC_SM_Reset_Seq
        ///	//Version: x.x
        ///	//Description: FC_SM_Reset_Seq
        ///	//Developer: Topcast
        ///	//********************************************************************//
        ///	
        ///	//UTILIZZO
        ///	//********************************************************************//
        ///	//Definire per ogni macchina  [stringa troncata]&quot;;.
        /// </summary>
        internal static string FC_SM_Reset_Seq {
            get {
                return ResourceManager.GetString("FC_SM_Reset_Seq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a         //$PHASE_NAME$
        ///        //********************************************************************// 
        ///    &quot;$PHASE_NAME$&quot;:
        ///        
        ///        &quot;FC_$PHASE_NAME$&quot;();.
        /// </summary>
        internal static string FC_SM_Step {
            get {
                return ResourceManager.GetString("FC_SM_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FUNCTION &quot;FC_SM_Stop_Seq&quot; : Void
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///   VAR_INPUT 
        ///      SMN : Int;
        ///   END_VAR
        ///
        ///
        ///BEGIN
        ///	//********************************************************************//
        ///	//Name: FC_SM_Stop_Seq
        ///	//Version: x.x
        ///	//Description: FC_SM_Stop_Seq
        ///	//Developer: Topcast
        ///	//********************************************************************//
        ///	
        ///	//UTILIZZO
        ///	//********************************************************************//
        ///	//Definire per ogni macchina a st [stringa troncata]&quot;;.
        /// </summary>
        internal static string FC_SM_Stop_Seq {
            get {
                return ResourceManager.GetString("FC_SM_Stop_Seq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TYPE &quot;AI_ALARM&quot;
        ///VERSION : 0.1
        ///   STRUCT
        ///      LowLimitExceeded : Bool;   // Allarme Limite inferiore superato
        ///      HighLimitExceeded : Bool;   // Allarme Limite superiore superato
        ///      SensorError : Bool;   // Allareme sensore scollegato o non funzionante
        ///   END_STRUCT;
        ///
        ///END_TYPE
        ///
        ///TYPE &quot;AI_AUX&quot;
        ///VERSION : 0.1
        ///   STRUCT
        ///      T_HighLimit {InstructionName := &apos;TON_TIME&apos;; LibVersion := &apos;1.0&apos;} : TON_TIME;
        ///      T_LowLimit {InstructionName := &apos;TON_TIME&apos;; LibVersion := &apos;1.0&apos;} : TON_TIME;
        ///      T_Se [stringa troncata]&quot;;.
        /// </summary>
        internal static string IO_Types {
            get {
                return ResourceManager.GetString("IO_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TYPE &quot;MSG_CONFIG&quot;
        ///VERSION : 0.1
        ///   STRUCT
        ///      Reaction : Array[0..$SM_TOT$] of Int := $ARRAY_LENGHT$($DEFAULT_REACTION$);   // Reazione Scaturita dal msg 0 = None,  1 = store, 2 = pause, 3 = Halt
        ///      Class : Int;
        ///      Nb : Int;
        ///   END_STRUCT;
        ///
        ///END_TYPE
        ///
        ///TYPE &quot;MSG_SQL&quot;
        ///VERSION : 0.1
        ///   STRUCT
        ///      Stored : Bool;
        ///      StoreForAll : Bool;   // Se 1 il msg viene salvato su SQL per tutti gli FO attivi su tutte le macchine a stati
        ///   END_STRUCT;
        ///
        ///END_TYPE
        ///
        ///TYPE &quot;MSG_GEN&quot;
        ///VERSION : 0.1
        /// [stringa troncata]&quot;;.
        /// </summary>
        internal static string Msg_Types {
            get {
                return ResourceManager.GetString("Msg_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TYPE &quot;SM_COMMANDS&quot;
        ///VERSION : 0.1
        ///   STRUCT
        ///      Start : Bool;   // Trigger che mette in play la macchina a stati
        ///      Pause : Bool;   // Trigger che mette in pausa la macchina a stati
        ///      Stop : Bool;   // Trigger che mette in pausa la macchina a stati
        ///      Reset : Bool;   // Trigger che resetta la macchina a stati
        ///   END_STRUCT;
        ///
        ///END_TYPE
        ///
        ///TYPE &quot;SM_FLAGS&quot;
        ///VERSION : 0.1
        ///   STRUCT
        ///      Release : Bool;   // Flag da utilizzare nel primo step della macchina a stati, si utilizza per interpola [stringa troncata]&quot;;.
        /// </summary>
        internal static string SM_Types {
            get {
                return ResourceManager.GetString("SM_Types", resourceCulture);
            }
        }
    }
}
